# PreToolUse guard for Edit/Write. Enforces two standing project rules that are
# cheap to check mechanically and so should never cost an agent turn:
#
#   1. roxygen2 generates man/*.Rd and NAMESPACE — edit the source, not the output
#   2. R comments describe the code, never its edit history
#
# Exit 0 allows the call; exit 2 blocks it and shows stderr to Claude.
# Any parsing problem exits 0: a guard that misfires is worse than one that
# occasionally misses, because a false block stops legitimate work.

try {
    $raw = [Console]::In.ReadToEnd()
    if ([string]::IsNullOrWhiteSpace($raw)) { exit 0 }
    $payload = $raw | ConvertFrom-Json
} catch {
    exit 0
}

$fp = $payload.tool_input.file_path
if ([string]::IsNullOrWhiteSpace($fp)) { exit 0 }
$norm = $fp -replace '\\', '/'

# --- rule 1: generated files -------------------------------------------------

if ($norm -match '/man/[^/]+\.Rd$' -or $norm -match '(^|/)NAMESPACE$') {
    [Console]::Error.WriteLine(@"
BLOCKED: $fp is generated by roxygen2 and must not be hand-edited.

Edit the roxygen block above the function in R/ instead, then regenerate:
  & "C:\Users\kdgc151\AppData\Local\Programs\R\R-4.4.2\bin\Rscript.exe" -e "roxygen2::roxygenise(load_code='source')"

Hand-edits here are silently reverted the next time anyone documents the package.
"@)
    exit 2
}

# --- rule 2: changelog comments in R sources ---------------------------------
# .R only. Rmd prose and NONMEM control streams (where FIX is a real keyword,
# e.g. "$THETA (0, 1 FIX)") must not be caught by this.

if ($norm -match '\.[Rr]$') {
    $text = ''
    foreach ($field in @('new_string', 'content')) {
        if ($payload.tool_input.PSObject.Properties.Name -contains $field) {
            $value = $payload.tool_input.$field
            if (-not [string]::IsNullOrEmpty($value)) { $text = [string]$value; break }
        }
    }

    if (-not [string]::IsNullOrEmpty($text)) {
        # Case-sensitive: only shouty changelog markers, so an ordinary comment
        # like "# recompute because the threshold changed" stays legal.
        $pattern = '(?m)^\s*#+.*\b(FIXED|ENHANCED|IMPROVED|UPDATED|NEW VERSION|OLD VERSION|WAS:)\b.*$'
        $hits = [regex]::Matches($text, $pattern)
        if ($hits.Count -gt 0) {
            $quoted = ($hits | ForEach-Object { '    ' + $_.Value.Trim() }) -join "`n"
            [Console]::Error.WriteLine(@"
BLOCKED: changelog-style comment(s) in $fp

$quoted

Comments describe what the code does, never how it changed. The edit history
lives in git. Either state the behavior plainly or drop the comment.
"@)
            exit 2
        }
    }
}

exit 0
